use mydb;
-- Insert user
insert into `user`(username,`password`,fullname,permission,created_at,updated_at) values
('admin','123','Nguyễn Quốc Ân', 1, current_timestamp(),null),
('mod','123','Ngô Thị T H', 2, current_timestamp(),null),
('an','123','Nguyễn A', 3, current_timestamp(),null),
('demo','123','Đỗ Demo', 3, current_timestamp(),null),
('anq','123','NQA', 3, current_timestamp(),null);
-- news
insert into news(`name`,preview,detail,author,`view`,picture,category_id,user_id,is_actived,created_at,updated_at) values
('Tổng Bí thư: Việt Nam - Lào xây đắp nên mối tình hữu nghị vĩ đại!', 'Tổng Bí thư Nguyễn Phú Trọng đã nhấn mạnh như vậy tại Lễ kỷ niệm 55 năm Ngày thiết lập quan hệ ngoại giao Việt Nam','Tham dự buổi Lễ, về phía Việt Nam có Tổng Bí thư Nguyễn Phú Trọng, nguyên Tổng Bí thư Lê Khả Phiêu, nguyên Tổng Bí thư Nông Đức Mạnh; Chủ tịch nước Trần Đại Quang, nguyên Chủ tịch nước Trần Đức Lương; Chủ tịch Quốc hội Nguyễn Thị Kim Ngân, nguyên Chủ tịch Quốc hội Nguyễn Sinh Hùng; Phó Thủ tướng Thường trực Chính phủ Trương Hòa Bình; Bí thư Thành ủy Hà Nội Hoàng Trung Hải; Chủ tịch Ủy ban Trung ương mặt trận Tổ quốc Việt Nam Trương Thanh Mẫn.','Châu Như Quỳnh',10,'viet-lao.jpg',1,1,1,current_timestamp(),null),
('9 người chết và mất tích sau bão số 2','Nguồn tin từ Ban Chỉ đạo Trung ương về phòng, chống thiên tai cho biết, tính đến 7h sáng nay (18/7),','Hiện vẫn còn 5 người mất tích, trong đó: 1 người tại Yên Bái là chị Hờ Thị Chi, 35 tuổi bị lũ cuốn khi đang trên đường đi làm và 4 thuyền viên tàu VTB26 bị lật chìm.','Nguyễn Thị A', 8,'bao-so2.jpg',4,2,1,current_timestamp(),null),
('Diễn viên Lý Hùng nói gì về những màn tỉ thí của cao thủ Vịnh Xuân?','Là một nghệ sĩ nhưng lại là thầy dạy võ, những ngày qua anh có theo dõi thường xuyên những','Mấy hôm nay, tôi cũng có theo dõi thông tin về võ sư Flores của cao thủ Vịnh Xuân Quyền qua báo chí. Tôi có xem qua một số màn tỉ thí của võ sư này với các võ sư Việt Nam.','Văn B', 12,'lyhung.jpg', 5,3,1,current_timestamp(),null),
('Mỹ giáng đòn khốc liệt chưa từng có vào sào huyệt của IS ở Syria','','','Hồ D',32,'my.jpg',3,4,1,current_timestamp(),null),
('MU - Real Salt Lake: "Bom tấn" nhả đạn, thẻ đỏ trớ trêu','Sau trận đại thắng LA Galaxy 5-2, MU tiếp tục hành trình du đấu trên đất Mỹ bằng chuyến làm khách trên sân Rio Tinto ','MU nhập cuộc không tốt do thể lực chưa đảm bảo khi vừa di chuyển hơn 1.000 km từ Los Angeles đến Utah chỉ trong 48 tiếng. Đội khách để cho Real Salt Lake có phần lấn lướt ở những phút đầu. Thậm chí, phút 23, đại diện xứ sở cờ hoa còn bất ngờ ghi bàn mở tỉ số sau khi Luis Saul Silva vượt qua Phil Jones rồi chích bóng tinh tế loại bỏ thủ thành trẻ Joel Castro.','Đứa con thần gió',23,'mu.jpg',2,5,1,current_timestamp(),null),
('Tổng Bí thư: Việt Nam - Lào xây đắp nên mối tình hữu nghị vĩ đại!', 'Tổng Bí thư Nguyễn Phú Trọng đã nhấn mạnh như vậy tại Lễ kỷ niệm 55 năm Ngày thiết lập quan hệ ngoại giao Việt Nam','Tham dự buổi Lễ, về phía Việt Nam có Tổng Bí thư Nguyễn Phú Trọng, nguyên Tổng Bí thư Lê Khả Phiêu, nguyên Tổng Bí thư Nông Đức Mạnh; Chủ tịch nước Trần Đại Quang, nguyên Chủ tịch nước Trần Đức Lương; Chủ tịch Quốc hội Nguyễn Thị Kim Ngân, nguyên Chủ tịch Quốc hội Nguyễn Sinh Hùng; Phó Thủ tướng Thường trực Chính phủ Trương Hòa Bình; Bí thư Thành ủy Hà Nội Hoàng Trung Hải; Chủ tịch Ủy ban Trung ương mặt trận Tổ quốc Việt Nam Trương Thanh Mẫn.','Châu Như Quỳnh',10,'viet-lao.jpg',1,1,1,current_timestamp(),null),
('9 người chết và mất tích sau bão số 2','Nguồn tin từ Ban Chỉ đạo Trung ương về phòng, chống thiên tai cho biết, tính đến 7h sáng nay (18/7),','Hiện vẫn còn 5 người mất tích, trong đó: 1 người tại Yên Bái là chị Hờ Thị Chi, 35 tuổi bị lũ cuốn khi đang trên đường đi làm và 4 thuyền viên tàu VTB26 bị lật chìm.','Nguyễn Thị A', 8,'bao-so2.jpg',4,2,1,current_timestamp(),null),
('Diễn viên Lý Hùng nói gì về những màn tỉ thí của cao thủ Vịnh Xuân?','Là một nghệ sĩ nhưng lại là thầy dạy võ, những ngày qua anh có theo dõi thường xuyên những','Mấy hôm nay, tôi cũng có theo dõi thông tin về võ sư Flores của cao thủ Vịnh Xuân Quyền qua báo chí. Tôi có xem qua một số màn tỉ thí của võ sư này với các võ sư Việt Nam.','Văn B', 12,'lyhung.jpg', 5,2,1,current_timestamp(),null),
('Mỹ giáng đòn khốc liệt chưa từng có vào sào huyệt của IS ở Syria','','','Hồ D',32,'my.jpg',3,4,1,current_timestamp(),null),
('MU - Real Salt Lake: "Bom tấn" nhả đạn, thẻ đỏ trớ trêu','Sau trận đại thắng LA Galaxy 5-2, MU tiếp tục hành trình du đấu trên đất Mỹ bằng chuyến làm khách trên sân Rio Tinto ','MU nhập cuộc không tốt do thể lực chưa đảm bảo khi vừa di chuyển hơn 1.000 km từ Los Angeles đến Utah chỉ trong 48 tiếng. Đội khách để cho Real Salt Lake có phần lấn lướt ở những phút đầu. Thậm chí, phút 23, đại diện xứ sở cờ hoa còn bất ngờ ghi bàn mở tỉ số sau khi Luis Saul Silva vượt qua Phil Jones rồi chích bóng tinh tế loại bỏ thủ thành trẻ Joel Castro.','Đứa con thần gió',23,'mu.jpg',2,5,1,current_timestamp(),null),
('Tổng Bí thư: Việt Nam - Lào xây đắp nên mối tình hữu nghị vĩ đại!', 'Tổng Bí thư Nguyễn Phú Trọng đã nhấn mạnh như vậy tại Lễ kỷ niệm 55 năm Ngày thiết lập quan hệ ngoại giao Việt Nam','Tham dự buổi Lễ, về phía Việt Nam có Tổng Bí thư Nguyễn Phú Trọng, nguyên Tổng Bí thư Lê Khả Phiêu, nguyên Tổng Bí thư Nông Đức Mạnh; Chủ tịch nước Trần Đại Quang, nguyên Chủ tịch nước Trần Đức Lương; Chủ tịch Quốc hội Nguyễn Thị Kim Ngân, nguyên Chủ tịch Quốc hội Nguyễn Sinh Hùng; Phó Thủ tướng Thường trực Chính phủ Trương Hòa Bình; Bí thư Thành ủy Hà Nội Hoàng Trung Hải; Chủ tịch Ủy ban Trung ương mặt trận Tổ quốc Việt Nam Trương Thanh Mẫn.','Châu Như Quỳnh',10,'viet-lao.jpg',1,1,1,current_timestamp(),null),
('9 người chết và mất tích sau bão số 2','Nguồn tin từ Ban Chỉ đạo Trung ương về phòng, chống thiên tai cho biết, tính đến 7h sáng nay (18/7),','Hiện vẫn còn 5 người mất tích, trong đó: 1 người tại Yên Bái là chị Hờ Thị Chi, 35 tuổi bị lũ cuốn khi đang trên đường đi làm và 4 thuyền viên tàu VTB26 bị lật chìm.','Nguyễn Thị A', 8,'bao-so2.jpg',4,2,1,current_timestamp(),null),
('Diễn viên Lý Hùng nói gì về những màn tỉ thí của cao thủ Vịnh Xuân?','Là một nghệ sĩ nhưng lại là thầy dạy võ, những ngày qua anh có theo dõi thường xuyên những','Mấy hôm nay, tôi cũng có theo dõi thông tin về võ sư Flores của cao thủ Vịnh Xuân Quyền qua báo chí. Tôi có xem qua một số màn tỉ thí của võ sư này với các võ sư Việt Nam.','Văn B', 12,'lyhung.jpg', 5,3,1,current_timestamp(),null),
('Mỹ giáng đòn khốc liệt chưa từng có vào sào huyệt của IS ở Syria','','','Hồ D',32,'my.jpg',3,4,1,current_timestamp(),null),
('MU - Real Salt Lake: "Bom tấn" nhả đạn, thẻ đỏ trớ trêu','Sau trận đại thắng LA Galaxy 5-2, MU tiếp tục hành trình du đấu trên đất Mỹ bằng chuyến làm khách trên sân Rio Tinto ','MU nhập cuộc không tốt do thể lực chưa đảm bảo khi vừa di chuyển hơn 1.000 km từ Los Angeles đến Utah chỉ trong 48 tiếng. Đội khách để cho Real Salt Lake có phần lấn lướt ở những phút đầu. Thậm chí, phút 23, đại diện xứ sở cờ hoa còn bất ngờ ghi bàn mở tỉ số sau khi Luis Saul Silva vượt qua Phil Jones rồi chích bóng tinh tế loại bỏ thủ thành trẻ Joel Castro.','Đứa con thần gió',23,'mu.jpg',2,5,1,current_timestamp(),null),
('Tổng Bí thư: Việt Nam - Lào xây đắp nên mối tình hữu nghị vĩ đại!', 'Tổng Bí thư Nguyễn Phú Trọng đã nhấn mạnh như vậy tại Lễ kỷ niệm 55 năm Ngày thiết lập quan hệ ngoại giao Việt Nam','Tham dự buổi Lễ, về phía Việt Nam có Tổng Bí thư Nguyễn Phú Trọng, nguyên Tổng Bí thư Lê Khả Phiêu, nguyên Tổng Bí thư Nông Đức Mạnh; Chủ tịch nước Trần Đại Quang, nguyên Chủ tịch nước Trần Đức Lương; Chủ tịch Quốc hội Nguyễn Thị Kim Ngân, nguyên Chủ tịch Quốc hội Nguyễn Sinh Hùng; Phó Thủ tướng Thường trực Chính phủ Trương Hòa Bình; Bí thư Thành ủy Hà Nội Hoàng Trung Hải; Chủ tịch Ủy ban Trung ương mặt trận Tổ quốc Việt Nam Trương Thanh Mẫn.','Châu Như Quỳnh',10,'viet-lao.jpg',1,1,1,current_timestamp(),null),
('9 người chết và mất tích sau bão số 2','Nguồn tin từ Ban Chỉ đạo Trung ương về phòng, chống thiên tai cho biết, tính đến 7h sáng nay (18/7),','Hiện vẫn còn 5 người mất tích, trong đó: 1 người tại Yên Bái là chị Hờ Thị Chi, 35 tuổi bị lũ cuốn khi đang trên đường đi làm và 4 thuyền viên tàu VTB26 bị lật chìm.','Nguyễn Thị A', 8,'bao-so2.jpg',4,2,1,current_timestamp(),null),
('Diễn viên Lý Hùng nói gì về những màn tỉ thí của cao thủ Vịnh Xuân?','Là một nghệ sĩ nhưng lại là thầy dạy võ, những ngày qua anh có theo dõi thường xuyên những','Mấy hôm nay, tôi cũng có theo dõi thông tin về võ sư Flores của cao thủ Vịnh Xuân Quyền qua báo chí. Tôi có xem qua một số màn tỉ thí của võ sư này với các võ sư Việt Nam.','Văn B', 12,'lyhung.jpg', 5,3,1,current_timestamp(),null),
('Mỹ giáng đòn khốc liệt chưa từng có vào sào huyệt của IS ở Syria','','','Hồ D',32,'my.jpg',3,4,1,current_timestamp(),null),
('MU - Real Salt Lake: "Bom tấn" nhả đạn, thẻ đỏ trớ trêu','Sau trận đại thắng LA Galaxy 5-2, MU tiếp tục hành trình du đấu trên đất Mỹ bằng chuyến làm khách trên sân Rio Tinto ','MU nhập cuộc không tốt do thể lực chưa đảm bảo khi vừa di chuyển hơn 1.000 km từ Los Angeles đến Utah chỉ trong 48 tiếng. Đội khách để cho Real Salt Lake có phần lấn lướt ở những phút đầu. Thậm chí, phút 23, đại diện xứ sở cờ hoa còn bất ngờ ghi bàn mở tỉ số sau khi Luis Saul Silva vượt qua Phil Jones rồi chích bóng tinh tế loại bỏ thủ thành trẻ Joel Castro.','Đứa con thần gió',23,'mu.jpg',3,4,0,current_timestamp(),null),
('Tổng Bí thư: Việt Nam - Lào xây đắp nên mối tình hữu nghị vĩ đại!', 'Tổng Bí thư Nguyễn Phú Trọng đã nhấn mạnh như vậy tại Lễ kỷ niệm 55 năm Ngày thiết lập quan hệ ngoại giao Việt Nam','Tham dự buổi Lễ, về phía Việt Nam có Tổng Bí thư Nguyễn Phú Trọng, nguyên Tổng Bí thư Lê Khả Phiêu, nguyên Tổng Bí thư Nông Đức Mạnh; Chủ tịch nước Trần Đại Quang, nguyên Chủ tịch nước Trần Đức Lương; Chủ tịch Quốc hội Nguyễn Thị Kim Ngân, nguyên Chủ tịch Quốc hội Nguyễn Sinh Hùng; Phó Thủ tướng Thường trực Chính phủ Trương Hòa Bình; Bí thư Thành ủy Hà Nội Hoàng Trung Hải; Chủ tịch Ủy ban Trung ương mặt trận Tổ quốc Việt Nam Trương Thanh Mẫn.','Châu Như Quỳnh',10,'viet-lao.jpg',1,1,1,current_timestamp(),null),
('9 người chết và mất tích sau bão số 2','Nguồn tin từ Ban Chỉ đạo Trung ương về phòng, chống thiên tai cho biết, tính đến 7h sáng nay (18/7),','Hiện vẫn còn 5 người mất tích, trong đó: 1 người tại Yên Bái là chị Hờ Thị Chi, 35 tuổi bị lũ cuốn khi đang trên đường đi làm và 4 thuyền viên tàu VTB26 bị lật chìm.','Nguyễn Thị A', 8,'bao-so2.jpg',4,2,1,current_timestamp(),null),
('Diễn viên Lý Hùng nói gì về những màn tỉ thí của cao thủ Vịnh Xuân?','Là một nghệ sĩ nhưng lại là thầy dạy võ, những ngày qua anh có theo dõi thường xuyên những','Mấy hôm nay, tôi cũng có theo dõi thông tin về võ sư Flores của cao thủ Vịnh Xuân Quyền qua báo chí. Tôi có xem qua một số màn tỉ thí của võ sư này với các võ sư Việt Nam.','Văn B', 12,'lyhung.jpg', 4,5,1,current_timestamp(),null),
('Mỹ giáng đòn khốc liệt chưa từng có vào sào huyệt của IS ở Syria','','','Hồ D',32,'my.jpg',3,4,1,current_timestamp(),null),
('MU - Real Salt Lake: "Bom tấn" nhả đạn, thẻ đỏ trớ trêu','Sau trận đại thắng LA Galaxy 5-2, MU tiếp tục hành trình du đấu trên đất Mỹ bằng chuyến làm khách trên sân Rio Tinto ','MU nhập cuộc không tốt do thể lực chưa đảm bảo khi vừa di chuyển hơn 1.000 km từ Los Angeles đến Utah chỉ trong 48 tiếng. Đội khách để cho Real Salt Lake có phần lấn lướt ở những phút đầu. Thậm chí, phút 23, đại diện xứ sở cờ hoa còn bất ngờ ghi bàn mở tỉ số sau khi Luis Saul Silva vượt qua Phil Jones rồi chích bóng tinh tế loại bỏ thủ thành trẻ Joel Castro.','Đứa con thần gió',23,'mu.jpg',1,1,1,current_timestamp(),null)
;
-- category
insert into category(`name`,created_at,updated_at) values
('Thời sự', current_timestamp(),null),
('Bóng đá', current_timestamp(),null),
('Chính trị', current_timestamp(),null),
('Xã hội', current_timestamp(),null),
('Sao Online', current_timestamp(),null);
